version: '3.8'

include:
  - proxy.yaml

services:

  web:
    hostname: web
    build: 
      context: .
      dockerfile: Dockerfile.python
    image: python-app
    restart: always
    networks:
        backend:
          ipv4_address: 172.20.0.5
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_TABLE_NAME=${MYSQL_TABLE_NAME}

  db:
    hostname: db
    image: mysql:8
    restart: always
    networks:
        backend:
          ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"